### ISSUE TITLE
Disable Dev Tools on shake registered

### ISSUE THREAD

**Issue by pawanbenjamin** [pawanbenjamin/zen-g-2024#4]
READ THE DOCS! Figure out how to disable shake on device (expo)

**Comment by russellwmoore** [comment]
Disabling shake to activate dev menu is possible on iOS but not Android (without a custom change to production build)
https://forums.expo.dev/t/disabling-shake-gesture-on-expo-go/59323
https://forums.expo.dev/t/disable-the-shake-menu-pop-up-even-in-production/45845
https://github.com/expo/expo/issues/3456
